### PR TITLE
DDS-1513 Publish token JSONs

### PR DESCRIPTION
**Pull request by yodas7**
As part of [DDS-1513](https://daikinsvoil.atlassian.net/browse/DDS-1513), we will provide information on what design tokens exist and what type/value they are, in preparation for integrating design tokens with the UI library Tailwind CSS.

This PR will build the following file:
スクリーンショット 2024-10-01 16 45 06

### CODE REVIEW

**Comment by yodas7** [comment]
I'd like to publish a new version of the library after merging this PR so that DDS can use this JSON.

**Comment by yodas7** [comment]
We're thinking of changing or adding output formats for Tailwind CSS.
However, I think it would probably be better to separate this change from this PR, so I will focus on JSON output only in this PR.

**Comment by hiro-daikin** [comment]
@yodas7 
Should we add your changes and additions to `README.md`?

Also, how do you plan on integrating this with tailwind?

It doesn't have to be part of this PR, but we would need to add documentation for these types of users:
1. Those that want to use the tailwind library to style their components
2. Those that just want to use the raw json values

**Comment by yodas7** [comment]
@hiro-daikin 
The integration with Tailwind CSS itself is in the PR for the DDS repository.
The basic idea is to:
- extend Tailwind CSS themes using `var(...)`
- for things that can't be achieved by extending the theme (e.g. specifying borders en masse), add utility classes using `var(...)`

The actual code is available at the following link:
https://github.com/dsv-rp/DDS/pull/76/files#diff-591d6b74dfc94d07f2ee21249afb18017a8f9bd702b70bb4938223ebc748f964

Perhaps these should eventually be moved to the dsv-rp/tailwind repository, but I think they should remain in the DDS repository during the exploratory phase.


I think that these JSONs are for use by DDS and are not included in the public API.
I will refer to the JSONs and mention this in the README.

**Comment by hiro-daikin** [comment]
@yodas7 
Thank you for the explanation.

Eventually, we would have to expose a file with all the variables. 
This can be css variables, or js values. 

We can think about that when it is needed.

**Review by hiro-daikin — DISMISSED** [review]

**Review by ukkary — APPROVED** [review]

**Pull request merged**
